variable "name_prefix" {}
variable "location" {}
variable "resource_group_name" {}
variable "storage_name" {}
variable "identity_id" {}
variable "storage_access_key" {}
variable "storage_blob_endpoint" {}
variable "code_container_name" {}
variable "static_site_url" {}
variable "cosmos_account_name" {}
variable "cosmos_table_name" {}
variable "cosmos_table_endpoint" {}
variable "cosmos_primary_key" {}
